[tool.poetry]
name = "PerfectFrameAI"
version = "2.2.0"
description = "AI tool for finding the most aesthetic frames in a video. ğŸï¸âœğŸ–¼ï¸"
authors = ["BartÅ‚omiej Flis <Bartekdawidflis@gmail.com>"]
license = "GPL-3.0 license"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"
numpy = "^1.26.4"
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
pytest-order = "^1.2.1"
httpx = "^0.27.0"
opencv-python = "^4.9.0.80"
requests = "^2.32.0"
tensorflow = "^2.16.1"
tensorflow-io-gcs-filesystem = "0.31.0"
docker = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
